#!/bin/bash

DIRECTORY="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

if [[ "$DIRECTORY" != ${HOME}* ]];then
  DIRECTORY="$HOME"
fi

[ -e "${DIRECTORY}/box86.download" ] && rm -rf "${DIRECTORY}/box86.download"
mkdir "${DIRECTORY}/box86.download"
cd "${DIRECTORY}/box86.download"

echo 'Downloading box86...'
wget https://archive.org/download/box86.7z_20200928/box86.tar.xz
wget https://archive.org/download/box86.7z_20200928/box86sum.txt -O "${DIRECTORY}/box86.hash"

echo "Extracting box86..."
tar xf ./box86.tar.xz
rm -f ./box86.tar.xz

echo "Installing files..."
sudo cp -avf "$(pwd)/etc"/* /etc
sudo cp -avf "$(pwd)/usr"/* /usr

cd
rm -rf "${DIRECTORY}/box86.download"
rm -rf "${DIRECTORY}/box86.hash"
echo -e "\nDone!"
